cd cppsdk
mkdir -p build/debug
cd build/debug
rm CMakeCache.txt
cmake ../.. \
  -DCMAKE_BUILD_TYPE=Debug \
  -DCMAKE_INSTALL_PREFIX="/usr/local" \
  -DBUILD_SHARED_LIBS=ON \
  -DCPPSDK_PLATFORM=PC_UNIX \
  -DCPPSDK_CRYPTALGO=ON \
  -DCPPSDK_DEVICES=ON \
  -DCPPSDK_GENERICS=ON \
  -DCPPSDK_PROCESS=ON \
  -DCPPSDK_RPC=ON \
  -DCPPSDK_TRACING=ON \
  -DCPPSDK_WEBSOCKET=ON \
  -DINSTALL_HEADERS_TO_TARGET=ON \
  -DCPPSDK_UNIT_TEST=ON \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
  -DCPPSDK_TEST_APPS=ON \
  -DCPPSDK_TEST_JSONTESTS=ON
make
cd ../../..

